# Permalinks
#
# Use of `relative_permalinks` ensures post links from the index work properly.
permalink:           pretty


# Setup
title:               Oscar Raig
tagline:             'El palau de la memòria'
description:         'El <a href="http://raig.cat" target="_blank">magatzem </a> dels meus records. Escrit per <a href="https://twitter.com/oscar_raig" target="_blank">@oscar_raig</a>.'
url:                 http://raig.cat
baseurl:             ''
gems: [jekyll-paginate]
paginate:            5
paginate_path: "page:num"

# About/contact
author:
  name:              Oscar Raig
  url:               https://twitter.com/oscar_raig
  email:             oscar.raig@gmail.com

# Custom vars
version:             1.0.0
